[package]
name = "rustyfinder"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
local-ip-address = "0.6.5"
qr2term = "0.3.3"
tiny_http = "0.12.0"
